import Head from 'next/head'
import { Inter } from 'next/font/google'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className='max-w-2xl mx-auto'>
          <nav className='my-4'>
          <Link href='/kelastrading' className='text-2xl font-bold hover:text-blue-700 underline'>Kelas Trading</Link>
          </nav>

          <section>
            <h1 className='text-4xl font-bold text-slate-500'>Hello, Andini!</h1>
          </section>
        </main>
    </>
  )
}
