import Head from 'next/head'
import Link from 'next/link'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const data = {title: "Arbitrase Internasional", id: 1, datePublished: "2023-02-16", dateModified: "2023-02-16"}
export default function Home() {
  console.log(data.title);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      <script type="application/ld+json">
{` [{
    "@context": "https://schema.org",
    "@type": "Article",
    "headline": "${data.title}",
    "datePublished": "${data.datePublished}",
    "dateModified": "${data.dateModified}",
  },
    {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [{
          "@type": "ListItem",
          "position": 1,
          "name": "Home",
          "item": "https://www.hsb.co.id/"
        },{
          "@type": "ListItem",
          "position": 2,
          "name": "Glosarium",
          "item": "https://www.hsb.co.id/glosarium"
        },{
          "@type": "ListItem",
          "position": 3,
          "name": "${data.title}"
        }]
      }
]` }
      </script>
      </Head>
      <Navbar />
      <main className='max-w-2xl mx-auto'>
        <section>
          <h1 className='text-4xl font-bold text-slate-500'>Hello, Andini!</h1>
        </section>
      </main>
      <Footer />
    </>
  )
}
