import Head from 'next/head'
import Link from 'next/link'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className='max-w-2xl mx-auto'>
        <section>
          <h1 className='text-4xl font-bold text-slate-500'>Hello, Andini!</h1>
        </section>
      </main>
      <Footer />
    </>
  )
}
